package com.xyecoc.mail.ui.theme

import androidx.compose.ui.graphics.Color

// Stitch Material You Light Palette
val md_theme_light_primary = Color(0xFF24389C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF3F51B5)
val md_theme_light_onPrimaryContainer = Color(0xFFCACFFF)
val md_theme_light_secondary = Color(0xFF585A8C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC3C4FE)
val md_theme_light_onSecondaryContainer = Color(0xFF4E5082)
val md_theme_light_tertiary = Color(0xFF583951)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF715069)
val md_theme_light_onTertiaryContainer = Color(0xFFF1C6E3)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFAF8FD)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFAF8FD)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E2E6)
val md_theme_light_onSurfaceVariant = Color(0xFF454652)
val md_theme_light_outline = Color(0xFF757684)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFBAC3FF)
val md_theme_light_surfaceTint = Color(0xFF4355B9)
val md_theme_light_outlineVariant = Color(0xFFC5C5D4)
val md_theme_light_scrim = Color(0xFF000000)

// Stitch Material You Dark Palette
val md_theme_dark_primary = Color(0xFFBAC3FF)
val md_theme_dark_onPrimary = Color(0xFF00105C)
val md_theme_dark_primaryContainer = Color(0xFF293CA0)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_secondary = Color(0xFFC0C2FB)
val md_theme_dark_onSecondary = Color(0xFF141545)
val md_theme_dark_secondaryContainer = Color(0xFF404273)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1E0FF)
val md_theme_dark_tertiary = Color(0xFFE5BAD7)
val md_theme_dark_onTertiary = Color(0xFF2C1228)
val md_theme_dark_tertiaryContainer = Color(0xFF5C3D54)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF141218)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1D1B20)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B20)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF24389C)
val md_theme_dark_surfaceTint = Color(0xFFBAC3FF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)

// OLED Black
val md_theme_oled_background = Color(0xFF000000)
val md_theme_oled_surface = Color(0xFF0F0E13)
val md_theme_oled_surfaceVariant = Color(0xFF232128)
